services:
  app:
    image: stac-fastapi-pgstac-pair-search
    build: .
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8082
      - RELOAD=true
      - ENVIRONMENT=local
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=postgis
      - PGHOST=database
      - PGPORT=5432
      - WEB_CONCURRENCY=10
      - VSI_CACHE=TRUE
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=1
      - USE_API_HYDRATE=${USE_API_HYDRATE:-false}
      - ENABLE_TRANSACTIONS_EXTENSIONS=TRUE
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    depends_on:
      - database
    command: bash -c "./scripts/wait-for-it.sh database:5432 && python -m stac_fastapi_pgstac_pair_search.app"

  database:
    image: ghcr.io/stac-utils/pgstac:v0.9.2
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgis
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=postgis
    volumes:
      - ./src/stac_fastapi_pgstac_pair_search/sql/n_diff.sql:/docker-entrypoint-initdb.d/n_diff.sql
      - ./src/stac_fastapi_pgstac_pair_search/sql/s_raoverlap.sql:/docker-entrypoint-initdb.d/s_raoverlap.sql
      - ./src/stac_fastapi_pgstac_pair_search/sql/t_diff.sql:/docker-entrypoint-initdb.d/t_diff.sql
      - ./src/stac_fastapi_pgstac_pair_search/sql/t_end.sql:/docker-entrypoint-initdb.d/t_end.sql
      - ./src/stac_fastapi_pgstac_pair_search/sql/t_start.sql:/docker-entrypoint-initdb.d/t_start.sql
    ports:
      - "5439:5432"
    command: postgres -N 500

  # Load test dataset into the PGStac Application
  load_test_data:
    image: stac-fastapi-pgstac-pair-search
    environment:
      - ENVIRONMENT=development
      - PGUSER=username
      - PGPASSWORD=password
      - PGDATABASE=postgis
      - PGHOST=database
      - PGPORT=5432
    volumes:
      - ./stac_fastapi:/app/stac_fastapi
      - ./scripts:/app/scripts
    command: >
      /bin/sh -c "
        ./scripts/wait-for-it.sh -t 60 app:8082 &&
        python -m pip install pip -U &&
        python -m pip install requests tqdm pystac_client pypgstac[psycopg] &&
        python /app/scripts/ingest_test_data.py http://app:8082
      "
    depends_on:
      - database
      - app

  # nginx:
  #   image: nginx
  #   ports:
  #     - ${STAC_FASTAPI_NGINX_PORT:-8080}:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - app-nginx
  #   command: [ "nginx-debug", "-g", "daemon off;" ]

  # app-nginx:
  #   extends:
  #     service: app
  #   command: bash -c "./scripts/wait-for-it.sh database:5432 && uvicorn src.stac_fastapi_pgstac_pair_search.app:app --host 0.0.0.0 --port 8082 --proxy-headers --forwarded-allow-ips=* --root-path=/api/v1/pgstac"
    
networks:
  default:
    name: stac-fastapi-network