CREATE OR REPLACE FUNCTION T_END(a TSRANGE)
RETURNS TIMESTAMPTZ AS $$
BEGIN
  RETURN UPPER(a);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION T_END(a TIMESTAMPTZ)
RETURNS TIMESTAMPTZ AS $$
BEGIN
  RETURN a;
END;
$$ LANGUAGE plpgsql;
