CREATE OR REPLACE FUNCTION T_START(a TSRANGE)
RETURNS TIMESTAMPTZ AS $$
BEGIN
  RETURN LOWER(a);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION T_START(a TIMESTAMPTZ)
RETURNS TIMESTAMPTZ AS $$
BEGIN
  RETURN a;
END;
$$ LANGUAGE plpgsql;
